provider:
  name: pihole

txtOwnerId: "lab"
policy: sync
logLevel: debug

image:
  repository: gcr.io/k8s-staging-external-dns/external-dns
  tag: v20250402-v0.16.1-48-g1efdf416

env:
  - name: EXTERNAL_DNS_PIHOLE_SERVER
    value: http://pihole-web.pihole.svc.cluster.local
  - name: EXTERNAL_DNS_PIHOLE_API_VERSION
    value: "6"
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: password

serviceAccount:
  name: externaldns
