vmsingle:
  spec:
    storage:
      resources:
        requests:
          storage: 1Gi

grafana:
  adminUser: admin
  adminPassword: admin

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin

  ingress:
    enabled: true
    hosts:
      - grafana.lab
